### ISSUE TITLE
I fixed Github Actions

### ISSUE THREAD

**Issue by styler00dollar** [media2x/realsr-ncnn-vulkan-python#1]
It seems like you tried to work on Github Actions and only Ubuntu currently works. In the past you had a different approach for Github Actions but that only ran cmake and did not produce the whl files. I fixed the process to build whl files for Ubuntu, Windows and Mac if you are interested. In your repo Windows currently fails because of [this](https://github.com/humbletim/setup-vulkan-sdk/issues/6) and I also added Python 3.10 everywhere, since Mac does use Python 2 by default (cmake extention wont install with pip) and it's nice to have the same version everywhere. You can see the built wheels yourself [here](https://github.com/styler00dollar/realsr-ncnn-vulkan-python/actions/runs/1812535583). Wanted to mention it in case you would be interested. My current code uses OpenCV numpy arrays instead of Pillow and I removed C++ tiling, so instead of making a pull request, due big differences, I just decided to just mention it in an issue.

Edit:
I also added a Python matrix for multiple versions, it is [here](https://github.com/styler00dollar/realsr-ncnn-vulkan-python/actions/runs/1813275894). It does build and upload everything, but for some reason it shows failed at the end since it tries to access a non-existent path. I am not sure how to fix that one.

**Comment by ArchieMeng** [comment]
Thank you for your suggestion. Well done.
We will discuss about it later.

**Comment by ArchieMeng** [comment]
> Can confirm the windows .whl has a DLL import problem. It installs fine, but when I try to import the package I get that error 

Could you provide the python version you used on windows? As far as I know, the binary wheel is strictly linked to python 3.10 on Windows.

**Comment by styler00dollar** [comment]
For my newest attempt with the version matrix, it seems like different versions all reference `python310.dll`, which might explain why every other version could fail.
```
C:\Users\Downloads\realsr-ncnn-vulkan-python-v1-windows_3.9.10\realsr_ncnn_vulkan_python>dumpbin /dependents _realsr_ncnn_vulkan_wrapper.pyd
Microsoft (R) COFF/PE Dumper Version 14.30.30709.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file _realsr_ncnn_vulkan_wrapper.pyd

File Type: DLL

  Image has the following dependencies:

    python310.dll
    libgcc_s_seh-1.dll
    KERNEL32.dll
    msvcrt.dll
    libwinpthread-1.dll
    libstdc++-6.dll
    libgomp-1.dll
    vulkan-1.dll
```
But when I try to install the 3.10.2 wheel into my own Python 3.10.2, I get the already mentioned error. Even if I take the whl from the non-matrix action, the same error appears. That wheel also mentions `python310.dll` and should be built and actually work with 3.10. 

Non-matrix 3.10 wheel:
[realsr-ncnn-vulkan-python-v1-windows.zip](https://github.com/media2x/realsr-ncnn-vulkan-python/files/8055292/realsr-ncnn-vulkan-python-v1-windows.zip)

Matrix wheels:
[realsr-ncnn-vulkan-python-v1-windows_3.10.2.zip](https://github.com/media2x/realsr-ncnn-vulkan-python/files/8055291/realsr-ncnn-vulkan-python-v1-windows_3.10.2.zip)

[realsr-ncnn-vulkan-python-v1-windows_3.9.10.zip](https://github.com/media2x/realsr-ncnn-vulkan-python/files/8055290/realsr-ncnn-vulkan-python-v1-windows_3.9.10.zip)

My only solution for now was to compile a 3.10 whl locally since all Windows whl files from Github Actions seem broken, but it would be nice if that can be fixed, since compiling different versions manually is quite time consuming. I sent the file to Joey and he said that the file I compiled myself with Visual Studio also didn't crash the import.

**Comment by joeyballentine** [comment]
> Could you provide the python version you used on windows? As far as I know, the binary wheel is strictly linked to python 3.10 on Windows.

I'm using 3.9 (that's the highest version pytorch supports). If it's hardcoded to 3.10 that would explain it. Why is it only for 3.10?

**Comment by ArchieMeng** [comment]
> > Could you provide the python version you used on windows? As far as I know, the binary wheel is strictly linked to python 3.10 on Windows.
> 
> I'm using 3.9 (that's the highest version pytorch supports). If it's hardcoded to 3.10 that would explain it. Why is it only for 3.10?

Because that's the python version used to build the library by default in the past.
Could you test if the latest windows wheels which is built with python version matrix solve the problem.

**Comment by joeyballentine** [comment]
I believe sudo said that he tested that wheel in 3.10.2 and it still did not work

**Comment by ArchieMeng** [comment]
> I believe styler00dollar said that he tested that wheel in 3.10.2 and it still did not work 

Yes, it is confirmed still broken.

Luckily, I have successfully built windows wheels with GitHub action in Waifu2x ncnn vulkan python project. If those wheels are confirmed working, then the fix will be applied to this project.

**Comment by ArchieMeng** [comment]
> > I believe styler00dollar said that he tested that wheel in 3.10.2 and it still did not work
> 
> Yes, it is confirmed still broken.
> 
> Luckily, I have successfully built windows wheels with GitHub action in Waifu2x ncnn vulkan python project. If those wheels are confirmed working, then the fix will be applied to this project.

Pre-releases are here: https://github.com/media2x/waifu2x-ncnn-vulkan-python/releases/tag/1.0.2rc1

**Comment by joeyballentine** [comment]
Unfortunately, I still get the error (Windows - Python 3.9)

>   File "C:\Users\Joey\AppData\Local\Programs\Python\Python39\lib\site-packages\waifu2x_ncnn_vulkan_python\waifu2x_ncnn_vulkan_wrapper.py", line 13, in <module>
    from . import _waifu2x_ncnn_vulkan_wrapper
ImportError: DLL load failed while importing _waifu2x_ncnn_vulkan_wrapper: The specified module could not be found.

**Comment by ArchieMeng** [comment]
> Unfortunately, I still get the error (Windows - Python 3.9)
> 
> > File "C:\Users\Joey\AppData\Local\Programs\Python\Python39\lib\site-packages\waifu2x_ncnn_vulkan_python\waifu2x_ncnn_vulkan_wrapper.py", line 13, in 
> > from . import _waifu2x_ncnn_vulkan_wrapper
> > ImportError: DLL load failed while importing _waifu2x_ncnn_vulkan_wrapper: The specified module could not be found.

Yes. I confirmed that there are some other problems in the build process. It uses GCC to build windows wheel, and making the result lib depends on libstdc++-6.dll and some other dlls.

**Comment by ArchieMeng** [comment]
> Unfortunately, I still get the error (Windows - Python 3.9)
> 
> > File "C:\Users\Joey\AppData\Local\Programs\Python\Python39\lib\site-packages\waifu2x_ncnn_vulkan_python\waifu2x_ncnn_vulkan_wrapper.py", line 13, in 
> > from . import _waifu2x_ncnn_vulkan_wrapper
> > ImportError: DLL load failed while importing _waifu2x_ncnn_vulkan_wrapper: The specified module could not be found.

How about 1.0.2rc2 releases? https://github.com/media2x/waifu2x-ncnn-vulkan-python/releases/tag/1.0.2rc2

**Comment by joeyballentine** [comment]
It no longer gives me that error, but it crashes python instead.

This is the output I got before it crashed:
> [0 NVIDIA GeForce RTX 3070 Ti]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 3070 Ti]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 3070 Ti]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 3070 Ti]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

**Comment by styler00dollar** [comment]
I tested the 1.0.2rc2 waifu ncnn and it works fine on my machine. Seems like Joeys error was image related.

I tried to put [release.yml](https://github.com/media2x/waifu2x-ncnn-vulkan-python/blob/201d846f28494430a09c4fedc157a2f999959bef/.github/workflows/release.yml) into my repo and [built some wheels](https://github.com/styler00dollar/realsr-ncnn-vulkan-python/actions/runs/1849114718). 18.04 also fails to build, so I removed it (`.so` not found error when it tries to finish compile).
```
C:\Users\realsr_ncnn_vulkan_python-1.0.0-cp39-cp39-win_amd64\realsr_ncnn_vulkan_python>dumpbin /dependents _realsr_ncnn_vulkan_wrapper.pyd
Microsoft (R) COFF/PE Dumper Version 14.30.30709.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file _realsr_ncnn_vulkan_wrapper.pyd

File Type: DLL

  Image has the following dependencies:

    vulkan-1.dll
    python310.dll
    KERNEL32.dll
    VCOMP140.DLL
```
```
    from . import _realsr_ncnn_vulkan_wrapper
ImportError: DLL load failed while importing _realsr_ncnn_vulkan_wrapper: Das angegebene Modul wurde nicht gefunden.
```
Seems like at least 3.10 seems to work, but the other versions still rely on `python310.dll` and fail to import. I have no idea why. Your waifu repo seems to work fine. Would be nice if you can try it on your own realsr repo.

**Comment by joeyballentine** [comment]
Also a small note: it actually does run ok for me on 3.9, it just still crashes python after running

**Comment by joeyballentine** [comment]
By the way, it's not a normal crash either, its a complete python failure
![image](https://user-images.githubusercontent.com/34788790/154161430-d564fcf0-8419-4a08-b28c-1ee1054c8d36.png)

**Comment by ArchieMeng** [comment]
> I tried to put [release.yml](https://github.com/media2x/waifu2x-ncnn-vulkan-python/blob/201d846f28494430a09c4fedc157a2f999959bef/.github/workflows/release.yml) into my repo and [built some wheels](https://github.com/styler00dollar/realsr-ncnn-vulkan-python/actions/runs/1849114718). 18.04 also fails to build, so I removed it (`.so` not found error when it tries to finish compile).
The ubuntu 18.04 build requires [Fix error in CMakeLists.txt setup.py branch](https://github.com/media2x/waifu2x-ncnn-vulkan-python/commit/f2d0e603c99515ddc2862e839c11e2f5b76a69d6).

> ```
> C:\Users\realsr_ncnn_vulkan_python-1.0.0-cp39-cp39-win_amd64\realsr_ncnn_vulkan_python>dumpbin /dependents _realsr_ncnn_vulkan_wrapper.pyd
> Microsoft (R) COFF/PE Dumper Version 14.30.30709.0
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> 
> Dump of file _realsr_ncnn_vulkan_wrapper.pyd
> 
> File Type: DLL
> 
>   Image has the following dependencies:
> 
>     vulkan-1.dll
>     python310.dll
>     KERNEL32.dll
>     VCOMP140.DLL
> ```
> 
> ```
>     from . import _realsr_ncnn_vulkan_wrapper
> ImportError: DLL load failed while importing _realsr_ncnn_vulkan_wrapper: Das angegebene Modul wurde nicht gefunden.
> ```
> 
> Seems like at least 3.10 seems to work, but the other versions still rely on `python310.dll` and fail to import. I have no idea why. Your waifu repo seems to work fine. Would be nice if you can try it on your own realsr repo.

The windows build with specific python version of development libs requires [ Update setup.py and CMakeLists.txt to allow building with specific python version](https://github.com/media2x/waifu2x-ncnn-vulkan-python/commit/16c4a254d5dc7ada3bd7dfbd77e168da59d26081)

And from your dump of _realsr_ncnn_vulkan_wrapper.pyd dependents, it is clear that the binary build requires VCOMP140.DLL which is a part of Visual C++ runtime 2015 to 2019

**Comment by styler00dollar** [comment]
Thanks for pointing out what was wrong. I did not notice these changes. 18.04 does build now and the other Python versions also work now for Windows. The whl are now pointing to the correct `python3X.dll`. I am closing this issue since all mentioned problems are resolved now. Thanks for helping.
